import shose from '../assets/shose.png'; 
import shose2 from '../assets/shose2.jpg'; 
import shose3 from '../assets/shose3.jpg'; 
const products = [
    {
        id: 'product1',
        name: 'valour blue',
        company: 'Nike',
        imageUrl: 'https://secure-images.nike.com/is/image/DotCom/CT8532_104_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'The Air Jordan 3 Valor Blue combines style and Performance for basketball enthusiasts.',
        price: "$72.00", 
    },
    {
        id: 'product2',
        name: 'jordan mars',
        company: 'Adidas',
        imageUrl: 'https://secure-images.nike.com/is/image/DotCom/CV3042_001_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'Inspired by Londons urban landscape, the jordan Mars 270 combines street style with modern comfort.',        
        price: "$100.00",   
        discount: "$120"     
    }, 
    {
        id: 'product3',
        name: 'racer blue',
        company: 'Nike',
        imageUrl: '	https://secure-images.nike.com/is/image/DotCom/CK6637_104_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'The Air Jordan 1 Zoom Racer Blue brings comfort and style to the streets with Zoom Air cushioning',        
        price: "$120.00",         
    }, 
    {
        id: 'product4',
        name: 'valour blue',
        company: 'Nike',
        imageUrl: 'https://secure-images.nike.com/is/image/DotCom/CT8532_104_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'The Air Jordan 3 Valor Blue combines style and Performance for basketball enthusiasts.',
        price: "$72.00", 
    },
    {
        id: 'product5',
        name: 'jordan mars',
        company: 'Adidas',
        imageUrl: 'https://secure-images.nike.com/is/image/DotCom/CV3042_001_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'Inspired by Londons urban landscape, the jordan Mars 270 combines street style with modern comfort.',        
        price: "$100.00",   
        discount: "$120"     
    }, 
    {
        id: 'product6',
        name: 'racer blue',
        company: 'Nike',
        imageUrl: '	https://secure-images.nike.com/is/image/DotCom/CK6637_104_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'The Air Jordan 1 Zoom Racer Blue brings comfort and style to the streets with Zoom Air cushioning',        
        price: "$120.00",         
    }, 
    {
        id: 'product7',
        name: 'cosmic unity',
        company: 'Nike',
        imageUrl: shose, 
        description: 'Disgned for the demands of the game, the Cosmic Unity Basketabll Shoe delivers responsive cushioning',        
        price: "$72.00",         
    }, 
    {
        id: 'product8',
        name: 'vans',
        company: 'Nike',
        imageUrl: shose2, 
        description: 'The Nike React Infinity Run Flykint ensures a smooth ride with lightweight and breathable materials.',        
        price: "$90.00",         
    }, 
    {
        id: 'product9',
        name: 'nike',
        company: 'Adidas',
        imageUrl: shose3, 
        description: 'The Nike React Miler ensures a comfortable and stable running experience With React Foam technology.',        
        price: "$30.00",         
    }, 
    {
        id: 'product10',
        name: 'valour blue',
        company: 'Nike',
        imageUrl: 'https://secure-images.nike.com/is/image/DotCom/CT8532_104_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'The Air Jordan 3 Valor Blue combines style and Performance for basketball enthusiasts.',
        price: "$72.00", 
    },
    {
        id: 'product11',
        name: 'jordan mars',
        company: 'Adidas',
        imageUrl: 'https://secure-images.nike.com/is/image/DotCom/CV3042_001_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'Inspired by Londons urban landscape, the jordan Mars 270 combines street style with modern comfort.',        
        price: "$100.00",   
        discount: "$120"     
    }, 
    {
        id: 'product12',
        name: 'racer blue',
        company: 'Nike',
        imageUrl: '	https://secure-images.nike.com/is/image/DotCom/CK6637_104_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'The Air Jordan 1 Zoom Racer Blue brings comfort and style to the streets with Zoom Air cushioning',        
        price: "$120.00",         
    },   
    {
        id: 'product13',
        name: 'cosmic unity',
        company: 'Nike',
        imageUrl: shose, 
        description: 'Disgned for the demands of the game, the Cosmic Unity Basketabll Shoe delivers responsive cushioning',        
        price: "$72.00",         
    }, 
    {
        id: 'product14',
        name: 'vans',
        company: 'Nike',
        imageUrl: shose2, 
        description: 'The Nike React Infinity Run Flykint ensures a smooth ride with lightweight and breathable materials.',        
        price: "$90.00",         
    }, 
    {
        id: 'product15',
        name: 'nike',
        company: 'Adidas',
        imageUrl: shose3, 
        description: 'The Nike React Miler ensures a comfortable and stable running experience With React Foam technology.',        
        price: "$30.00",         
    }, 
    {
        id: 'product16',
        name: 'valour blue',
        company: 'Nike',
        imageUrl: 'https://secure-images.nike.com/is/image/DotCom/CT8532_104_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'The Air Jordan 3 Valor Blue combines style and Performance for basketball enthusiasts.',
        price: "$72.00", 
    },
    {
        id: 'product17',
        name: 'jordan mars',
        company: 'Adidas',
        imageUrl: 'https://secure-images.nike.com/is/image/DotCom/CV3042_001_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'Inspired by Londons urban landscape, the jordan Mars 270 combines street style with modern comfort.',        
        price: "$100.00",   
        discount: "$120"     
    }, 
    {
        id: 'product18',
        name: 'racer blue',
        company: 'Nike',
        imageUrl: '	https://secure-images.nike.com/is/image/DotCom/CK6637_104_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'The Air Jordan 1 Zoom Racer Blue brings comfort and style to the streets with Zoom Air cushioning',        
        price: "$120.00",         
    }, 
    {
        id: 'product19',
        name: 'cosmic unity',
        company: 'Nike',
        imageUrl: shose, 
        description: 'Disgned for the demands of the game, the Cosmic Unity Basketabll Shoe delivers responsive cushioning',        
        price: "$72.00",         
    }, 
    {
        id: 'product20',
        name: 'jordan mars',
        company: 'Adidas',
        imageUrl: 'https://secure-images.nike.com/is/image/DotCom/CV3042_001_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'Inspired by Londons urban landscape, the jordan Mars 270 combines street style with modern comfort.',        
        price: "$100.00",   
        discount: "$120"     
    }, 
    {
        id: 'product21',
        name: 'cosmic unity',
        company: 'Nike',
        imageUrl: shose, 
        description: 'Disgned for the demands of the game, the Cosmic Unity Basketabll Shoe delivers responsive cushioning',        
        price: "$72.00",         
    }, 
    {
        id: 'product22',
        name: 'cosmic unity',
        company: 'Nike',
        imageUrl: shose3, 
        description: 'Disgned for the demands of the game, the Cosmic Unity Basketabll Shoe delivers responsive cushioning',        
        price: "$72.00",         
    }, 
    {
        id: 'product23',
        name: 'jordan mars',
        company: 'Adidas',
        imageUrl: 'https://secure-images.nike.com/is/image/DotCom/CV3042_001_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'Inspired by Londons urban landscape, the jordan Mars 270 combines street style with modern comfort.',        
        price: "$100.00",   
        discount: "$120"     
    }, 
    {
        id: 'product24',
        name: 'cosmic unity',
        company: 'Nike',
        imageUrl: shose, 
        description: 'Disgned for the demands of the game, the Cosmic Unity Basketabll Shoe delivers responsive cushioning',        
        price: "$72.00",         
    }, 
    {
        id: 'product25',
        name: 'cosmic unity',
        company: 'Nike',
        imageUrl: shose3, 
        description: 'Disgned for the demands of the game, the Cosmic Unity Basketabll Shoe delivers responsive cushioning',        
        price: "$72.00",         
    }, 
    {
        id: 'product26',
        name: 'jordan mars',
        company: 'Adidas',
        imageUrl: 'https://secure-images.nike.com/is/image/DotCom/CV3042_001_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'Inspired by Londons urban landscape, the jordan Mars 270 combines street style with modern comfort.',        
        price: "$100.00",   
        discount: "$120"     
    }, 
    {
        id: 'product27',
        name: 'cosmic unity',
        company: 'Nike',
        imageUrl: shose, 
        description: 'Disgned for the demands of the game, the Cosmic Unity Basketabll Shoe delivers responsive cushioning',        
        price: "$72.00",         
    }, 
    {
        id: 'product28',
        name: 'valour blue',
        company: 'Nike',
        imageUrl: 'https://secure-images.nike.com/is/image/DotCom/CT8532_104_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'The Air Jordan 3 Valor Blue combines style and Performance for basketball enthusiasts.',
        price: "$72.00", 
    },
    {
        id: 'product29',
        name: 'racer blue',
        company: 'Nike',
        imageUrl: '	https://secure-images.nike.com/is/image/DotCom/CK6637_104_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'The Air Jordan 1 Zoom Racer Blue brings comfort and style to the streets with Zoom Air cushioning',        
        price: "$120.00",         
    }, 
    {
        id: 'product30',
        name: 'vans',
        company: 'Nike',
        imageUrl: shose2, 
        description: 'The Nike React Infinity Run Flykint ensures a smooth ride with lightweight and breathable materials.',        
        price: "$90.00",         
    }, 
    {
        id: 'product31',
        name: 'valour blue',
        company: 'Nike',
        imageUrl: 'https://secure-images.nike.com/is/image/DotCom/CT8532_104_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'The Air Jordan 3 Valor Blue combines style and Performance for basketball enthusiasts.',
        price: "$72.00", 
    },
    {
        id: 'product32',
        name: 'racer blue',
        company: 'Nike',
        imageUrl: '	https://secure-images.nike.com/is/image/DotCom/CK6637_104_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'The Air Jordan 1 Zoom Racer Blue brings comfort and style to the streets with Zoom Air cushioning',        
        price: "$120.00",         
    }, 
    {
        id: 'product33',
        name: 'vans',
        company: 'Nike',
        imageUrl: shose2, 
        description: 'The Nike React Infinity Run Flykint ensures a smooth ride with lightweight and breathable materials.',        
        price: "$90.00",         
    }, 
    {
        id: 'product34',
        name: 'valour blue',
        company: 'Nike',
        imageUrl: 'https://secure-images.nike.com/is/image/DotCom/CT8532_104_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'The Air Jordan 3 Valor Blue combines style and Performance for basketball enthusiasts.',
        price: "$72.00", 
    },
    {
        id: 'product35',
        name: 'racer blue',
        company: 'Nike',
        imageUrl: '	https://secure-images.nike.com/is/image/DotCom/CK6637_104_A_PREM?$SNKRS_COVER_WD$&align=0,1', 
        description: 'The Air Jordan 1 Zoom Racer Blue brings comfort and style to the streets with Zoom Air cushioning',        
        price: "$120.00",         
    },    
];
export default products;